### ISSUE TITLE
failed test

### ISSUE THREAD

**Issue by RyanSinger** [namecoin/namecore#11] opened 2015-06-11 00:15 UTC
===============================================
   Namecoin Core 0.11.99: src/test-suite.log
===============================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: qt/test/test_bitcoin-qt
=============================

********* Start testing of URITests *********
Config: Using QtTest library 5.4.2, Qt 5.4.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 6.1.0 (clang-602.0.53) (Apple))
PASS   : URITests::initTestCase()
FAIL!  : URITests::uriTests() 'GUIUtil::parseBitcoinURI(uri, &rv)' returned FALSE. ()
   Loc: [qt/test/uritests.cpp(20)]
PASS   : URITests::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted
********* Finished testing of URITests *********
********* Start testing of PaymentServerTests *********
Config: Using QtTest library 5.4.2, Qt 5.4.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 6.1.0 (clang-602.0.53) (Apple))
PASS   : PaymentServerTests::initTestCase()
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::initNetManager: No active proxy server found.
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Secure payment request from  "testmerchant.org"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate( "3" , "03" , "LxHILx+N3qwVoAcCmQ5cyw==" , () , ("Expired Test Merchant") , QMap() , QDateTime("2013-02-23 21:26:43.000 UTC Qt::UTC") , QDateTime("2013-02-24 21:26:43.000 UTC Qt::UTC") )
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "NACCXtKxpS66dzKujvjv4oPK1ES7H5ybnP"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate( "3" , "03" , "LxHILx+N3qwVoAcCmQ5cyw==" , () , ("Expired Test Merchant") , QMap() , QDateTime("2013-02-23 21:26:43.000 UTC Qt::UTC") , QDateTime("2013-02-24 21:26:43.000 UTC Qt::UTC") )
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Secure payment request from  "testmerchant8.org"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate( "3" , "06" , "MiZaQ+g9lSHZGuHWkXZG+g==" , () , ("Payment Request Intermediate 5") , QMap() , QDateTime("2013-02-23 22:59:51.000 UTC Qt::UTC") , QDateTime("2013-02-24 22:59:51.000 UTC Qt::UTC") )
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "NACCXtKxpS66dzKujvjv4oPK1ES7H5ybnP"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: Payment request: certificate expired or not yet active:  QSslCertificate( "3" , "06" , "MiZaQ+g9lSHZGuHWkXZG+g==" , () , ("Payment Request Intermediate 5") , QMap() , QDateTime("2013-02-23 22:59:51.000 UTC Qt::UTC") , QDateTime("2013-02-24 22:59:51.000 UTC Qt::UTC") )
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  certificate signature failure
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "NACCXtKxpS66dzKujvjv4oPK1ES7H5ybnP"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  certificate signature failure
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  unable to get local issuer certificate
QDEBUG : PaymentServerTests::paymentServerTests() PaymentServer::processPaymentRequest: Insecure payment request to  "NACCXtKxpS66dzKujvjv4oPK1ES7H5ybnP"
QWARN  : PaymentServerTests::paymentServerTests() PaymentRequestPlus::getMerchant: SSL error:  unable to get local issuer certificate
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyNetwork: Payment request network "test" doesn't match client network "main"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyExpired: Payment request expired "1970-01-01 00:00:01"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyExpired: Payment request expired "1970-01-01 00:00:00"."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::readPaymentRequestFromFile: Payment request /var/folders/kk/_xd1xzj90cj_0zz59yprzjrc0000gn/T/Bitcoin-Qt-test.M39831 is too large (50001 bytes, allowed 50000 bytes)."
QWARN  : PaymentServerTests::paymentServerTests() "PaymentServer::verifyAmount: Payment request amount out of allowed range (2100000100000000, allowed 0 - 2100000000000000)."
PASS   : PaymentServerTests::paymentServerTests()
PASS   : PaymentServerTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted
********* Finished testing of PaymentServerTests *********
FAIL qt/test/test_bitcoin-qt (exit status: 1)

**Comment by JeremyRand** [comment] 2015-08-03 02:19
@domob1812 Are you able to reproduce this?

**Comment by domob1812** [comment] 2015-08-03 04:40
This test used to fail due to not having adapted the bitcoin: to namecoin: URIs.  This was fixed some time ago, and as far as I can tell, it works for me now.  I'm not sure whether this issue was reported before or after fixing it.  I. e., currently I can not reproduce it, but I'm not sure if this is only me or the issue here was fixed already.  I guess it is the latter, but please try yourself.  If it works for you as well, feel free to close the issue.

**Closed** 2015-08-22 17:35 UTC
