### ISSUE TITLE
Crash bug reported by Eligius

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecore#25] opened 2015-08-07 21:40 UTC
[10:14:25] <wizkid057> Eligius namecoind crashed ~6 hours ago, nothing telling in debug log
    [10:15:23] <wizkid057> by contrast the old version I had going had an uptime of over a year
    [10:17:10] <wizkid057> actually, nm... it crashed again on restart
    [10:17:16] <wizkid057> namecoind: /home/ubuntu/build/namecoin/depends/i686-pc-linux-gnu/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = CReserveScript, typename boost::detail::sp_member_access<T>::type = CReserveScript*]: Assertion `px != 0' failed.
    [10:17:44] <wizkid057> yep, wont restart now
    [10:20:03] <Squidicuz> HEY! I am supposed to make a ticket about
    [10:20:07] <Squidicuz> that
    [10:20:09] <Squidicuz> .__.
    [10:21:57] <Squidicuz> namecoind: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = CReserveScript; typename boost::detail::sp_member_access<T>::type = CReserveScript*]: Assertion `px != 0' failed.
    [10:22:19] <wizkid057> pretty sure the wallet keypool is exhausted... testing that theory
    [10:23:03] <Squidicuz> I am using p2pool, everytime the RPC from p2pool connects to namecore, I get that.  I compiled namecore with wallet disabled :s
    [10:23:13] <Squidicuz> Does it need the wallet? :
    [10:23:45] <wizkid057> most likely in that scenario
    [10:24:06] <wizkid057> since you're generating coins they have to go somewhere, unless you have something else making templates for namecoin
    [10:24:06] <Squidicuz> feck. okay
    [10:25:34] <wizkid057> not sure why I never had this problem before.  it would just complain the keypool was exhausted or something previously, but wouldn't crash
    [10:26:09] <Squidicuz> hmmph
    [10:26:51] <wizkid057> that was with a version from like, 2 years ago though :)
    [10:29:09] <Squidicuz> yeah, that was what I was using too.. upgraded and uhhh..
    [11:26:10] <Squidicuz> wizkid057, yup that was my issue!  recompiled with wallet enabled, imagine that, it works now

**Comment by JeremyRand** [comment] 2015-08-08 01:03
Note that I'm not certain that the two issues involved have the same underlying cause.

**Comment by JeremyRand** [comment] 2015-08-09 05:30
[Saturday, August 08, 2015] [08:46:53 PM] <Jeremy_Rand> wizkid057: did you find a workaround to the namecoind crashing issue you were having?
    [05:21:41] <wizkid057> Jeremy_Rand: workaround was to block it from the network while I did a keypool refill
    [05:22:35] <Jeremy_Rand> wizkid057: ok.  So you got it working short-term, at least?
    [05:23:28] <wizkid057> should be long term since i refilled with 50000 keys, but yeah lol
    [05:24:12] <Jeremy_Rand> wizkid057: ok.  So it's not urgent for us to get fixed, at least from your end?
    [05:25:09] <wizkid057> not for me, but I'm sure someone else will eventually run into the issue and not know a workaround
    [05:25:36] <Jeremy_Rand> wizkid057: agreed.  We will certainly try to get it fixed as soon as possible.
    [05:26:03] <Jeremy_Rand> Thanks for the bug report
    [05:26:12] <wizkid057> basically getauxblock needs to not crash namecoind and properly report that the keypool is empty
    [05:26:23] <Jeremy_Rand> yeah
    [05:26:45] <wizkid057> perhaps it could even... *gulp* reuse an old address in the meantime
    [05:26:47] * wizkid057 runs
    [05:27:09] <Jeremy_Rand> heh

**Comment by domob1812** [comment] 2015-08-09 08:14
Sounds good.  I'll look into this when I have time.  It is probably easy to fix once I have everything set up to reproduce it.

**Comment by domob1812** [comment] 2015-08-18 07:10
This is caused by a bug introduced recently upstream in Bitcoin; see https://github.com/bitcoin/bitcoin/pull/6567.  When my patch for it is merged there, I will implement a fix for `getauxblock` as well for Namecoin.

**Comment by domob1812** [comment] 2015-08-20 06:36
Fixed on my auxpow branch in https://github.com/domob1812/namecore/commit/eb6be23fb430c05f2488c3843ea3bc72cb3e1ffd.  I will merge this into master next and push everything to Namecoin Core's repository (including latest Bitcoin patches as well).  Closing this.

**Closed by domob1812** 2015-08-20 06:36 UTC
